baseurl = "/"
languageCode = "en-us"
title = "Robert Huang"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
    description = "A website built through Hugo and blogdown."
    footer = "[XMin](https://github.com/yihui/hugo-xmin/) theme for [Hugo](https://gohugo.io/)."