---
title: NBA Awards Voting - Hometown Bias
author: Robert Huang
date: '2018-11-13'
slug: nba-awards-voting-hometown-bias
categories: []
tags:
  - NBA
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<link href="/rmarkdown-libs/htmltools-fill/fill.css" rel="stylesheet" />
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<link href="/rmarkdown-libs/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="/rmarkdown-libs/datatables-binding/datatables.js"></script>
<script src="/rmarkdown-libs/jquery/jquery-3.6.0.min.js"></script>
<link href="/rmarkdown-libs/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="/rmarkdown-libs/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="/rmarkdown-libs/dt-core/js/jquery.dataTables.min.js"></script>
<link href="/rmarkdown-libs/crosstalk/css/crosstalk.min.css" rel="stylesheet" />
<script src="/rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="/rmarkdown-libs/htmltools-fill/fill.css" rel="stylesheet" />
<script src="/rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="/rmarkdown-libs/plotly-binding/plotly.js"></script>
<script src="/rmarkdown-libs/typedarray/typedarray.min.js"></script>
<script src="/rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="/rmarkdown-libs/crosstalk/css/crosstalk.min.css" rel="stylesheet" />
<script src="/rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="/rmarkdown-libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="/rmarkdown-libs/plotly-main/plotly-latest.min.js"></script>
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>

<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />

## Background

The end of season awards for the NBA are voted upon by a panel of media members that include national writers, national broadcasters/announcers, studio analysts, and team beat writers. Up until the 2016-17 season, this group also included team employed broadcasters. NBA fans who have spent enough time watching games on League Pass may have noticed why this was an issue, with hometown biases among many local announcers evident during the call of games. There was nothing to stop this homerism from seeping into awards voting. This was especially an issue when the amount of money available for player contracts sometimes depended on how the player performed in the awards.

The NBA [stopped](https://basketball.realgm.com/wiretap/245507/NBA-Removes-Team-Employed-Media-From-Award-Voting) this practice starting with the awards for the 2016-17 season, no longer giving ballots to team-employed media members. About 70-80 local radio and TV announcers who voted after the 2013-14, 2014-15, and 2015-16 seasons were not able to participate in the vote anymore. Other non-team employed, but still team associated media, continued to receive ballots. This includes beat writers and local analysts. While not team employees, they could be susceptible to the same biases as the local announcers given the amount of time they spend around a specific team.

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Year
</th>
<th style="text-align:right;">
Total Voters
</th>
<th style="text-align:right;">
Team-Affiliated
</th>
<th style="text-align:right;">
Percent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
13/14
</td>
<td style="text-align:right;">
165
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
0.79
</td>
</tr>
<tr>
<td style="text-align:left;">
14/15
</td>
<td style="text-align:right;">
172
</td>
<td style="text-align:right;">
138
</td>
<td style="text-align:right;">
0.80
</td>
</tr>
<tr>
<td style="text-align:left;">
15/16
</td>
<td style="text-align:right;">
177
</td>
<td style="text-align:right;">
145
</td>
<td style="text-align:right;">
0.82
</td>
</tr>
<tr>
<td style="text-align:left;">
16/17
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
0.40
</td>
</tr>
<tr>
<td style="text-align:left;">
17/18
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
0.42
</td>
</tr>
</tbody>
</table>

With the change in voting, the percentage of voters who had team-affiliations declined from about 80% in the three-year period from 2013/14 to 2015/16 to about 40% these last two seasons. Note that the panel of voters is not the same every year and that not every member voted in every category. Every ballot since the 2013-14 awards has been [made](http://official.nba.com/2014-nba-year-annual-award-voting-results/) [public](http://official.nba.com/2015-nba-year-annual-award-voting-results/) [by](http://official.nba.com/2015-16-nba-annual-award-voting-results/)
[the](http://official.nba.com/2016-17-nba-annual-award-voting-results/)
[NBA](http://pr.nba.com/voting-results-2017-18-nba-regular-season-awards/). This makes it possible to analyze the overall results from the last five seasons in detail for hometown bias. We will attempt to quantify this bias among team-affiliated media members to identify the voters most or least abusing their awards ballots and whether any of the remaining team-affiliated voters (almost all beat writers) show any team biases.

## Quantifying Hometown Bias

Before any calculations for hometown bias, we must link voters to a hometown team (or teams if multiple affiliations), if applicable. This is simple for local announcers and beat writers. The voters without any team affiliation are generally national TV broadcasters/analysts (Rachel Nichols, Ernie Johnson, Chris Webber, etc.) or writers for national outlets without a focus on a specific team (Zach Lowe, Sean Deveney, Lang Whitaker, etc.). International media started voting in in 2016-17 and also do not have team affiliations. The area where this gets tricky is with a few national writers who have a link to a specific team. Brian Windhorst and Jackie MacMullan are national writers for ESPN, but both have generally had a focus on a specific team. For Windhorst, this is any team that LeBron James is on. For MacMullan, this is Boston Celtics. There are few situations like this and any determinations of team affiliation are judgement calls. Once every non-national voter is linked with a team, we can try to measure homerism.

#### Step 1: Compare where each team-affiliated voter places players from his or her team on their ballot against those same players’ average positions on ballots from voters not associated with those players’ respective teams (place differential).

For any specific ballot, if a voter places a hometown player higher than average, this is evidence for hometown bias for that vote. Conversely, if a voter places a hometown player lower than average, this is evidence against bias.

Note that if a player is left completely off a ballot, that player is given a placement of last place plus one. For MVP, this will be sixth place because there are five slots for that award type. For Defensive Player, Coach, Sixth Man, Most Improved, and Rookie of the Year, this will be fourth place because those awards each have three slots. For the All-NBA, All-Defense, and All-Rookie teams, all of the first team are treated as first place, all of the second team are treated as second place, and so on. Under this method, we make the assumption that any player not voted for is only one place away from the lowest slot on each ballot. This is absolutely not true, but there is no way of quantifying how voters rate players they do not vote for.

#### Step 2: For each voter, sum the place differentials from step 1 for all hometown players for a specific year-award combination.

This results in an overall bias score for a voter’s ballot for a single award. Similarly to step one, a net positive differential signals possible hometown bias and a net negative differential signals possible anti-hometown bias.

As an example of these first two steps, we can look at Los Angeles Clipper play-by-play announcer Ralph Lawler’s 2015-16 ballot for All-NBA:

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Forward.1
</td>
<td style="text-align:left;">
Kawhi.Leonard
</td>
<td style="text-align:left;">
SAS
</td>
</tr>
<tr>
<td style="text-align:left;">
Forward.1
</td>
<td style="text-align:left;">
LeBron.James
</td>
<td style="text-align:left;">
CLE
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
Center.1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
DeAndre.Jordan
</td>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
LAC
</td>
</tr>
<tr>
<td style="text-align:left;">
Guard.1
</td>
<td style="text-align:left;">
Russell.Westbrook
</td>
<td style="text-align:left;">
OKC
</td>
</tr>
<tr>
<td style="text-align:left;">
Guard.1
</td>
<td style="text-align:left;">
Stephen.Curry
</td>
<td style="text-align:left;">
GSW
</td>
</tr>
<tr>
<td style="text-align:left;">
Forward.2
</td>
<td style="text-align:left;">
Kevin.Durant
</td>
<td style="text-align:left;">
OKC
</td>
</tr>
<tr>
<td style="text-align:left;">
Forward.2
</td>
<td style="text-align:left;">
Draymond.Green
</td>
<td style="text-align:left;">
GSW
</td>
</tr>
<tr>
<td style="text-align:left;">
Center.2
</td>
<td style="text-align:left;">
Andre.Drummond
</td>
<td style="text-align:left;">
DET
</td>
</tr>
<tr>
<td style="text-align:left;">
Guard.2
</td>
<td style="text-align:left;">
Klay.Thompson
</td>
<td style="text-align:left;">
GSW
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
Guard.2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
Chris.Paul
</td>
<td style="text-align:left;font-weight: bold;color: rgba(237, 23, 76, 255) !important;background-color: rgba(0, 107, 182, 255) !important;">
LAC
</td>
</tr>
<tr>
<td style="text-align:left;">
Forward.3
</td>
<td style="text-align:left;">
Anthony.Davis
</td>
<td style="text-align:left;">
NOP
</td>
</tr>
<tr>
<td style="text-align:left;">
Forward.3
</td>
<td style="text-align:left;">
Paul.George
</td>
<td style="text-align:left;">
IND
</td>
</tr>
<tr>
<td style="text-align:left;">
Center.3
</td>
<td style="text-align:left;">
DeMarcus.Cousins
</td>
<td style="text-align:left;">
SAC
</td>
</tr>
<tr>
<td style="text-align:left;">
Guard.3
</td>
<td style="text-align:left;">
Damian.Lillard
</td>
<td style="text-align:left;">
POR
</td>
</tr>
<tr>
<td style="text-align:left;">
Guard.3
</td>
<td style="text-align:left;">
Isaiah.Thomas
</td>
<td style="text-align:left;">
BOS
</td>
</tr>
</tbody>
</table>

The ballot has five first place votes (first team), five second place votes (second team), and five third place votes (third team). Of the 15 slots on the ballot, Lawler gave votes to two Clippers: DeAndre Jordan as first team center and Chris Paul as second team guard. We will compare Lawler’s votes with how Clippers performed on All-NBA ballots from all voters not affiliated with the Clippers:

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Player
</th>
<th style="text-align:right;">
Voters
</th>
<th style="text-align:right;">
Non-Team Voters
</th>
<th style="text-align:right;">
Non-Team Mentions
</th>
<th style="text-align:right;">
Non-Team Avg Place
</th>
<th style="text-align:right;">
1st
</th>
<th style="text-align:right;">
2nd
</th>
<th style="text-align:right;">
3rd
</th>
<th style="text-align:right;">
Place Differential
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Chris Paul
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
126
</td>
<td style="text-align:right;">
116
</td>
<td style="text-align:right;">
2.17
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
98
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0.17
</td>
</tr>
<tr>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
126
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
2.45
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1.45
</td>
</tr>
<tr>
<td style="text-align:left;">
Blake Griffin
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
126
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.99
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
-0.01
</td>
</tr>
</tbody>
</table>

There are 129 total ballots for 2013/14 All-NBA. Of those 129, 3 are from voters associated with the Clippers, leaving 126 non-Clipper ballots. With those 126 voters, 3 players from the Clippers received at least one vote. Chris Paul received 116 mentions (8 first team, 98 second team, 10 third team, and was left off of 10 ballots—“fourth place”), resulting in a mean placement of 2.17 from the non-Clipper voters. Lawler placed Paul second on his ballot, 0.17 places higher than average. Similarly for DeAndre Jordan, Lawler has him 1.45 places higher than average. Blake Griffin received one third place vote from other voters. By leaving Griffin off his ballot, Lawler has Griffin about 0.01 places lower than average. If we sum these place differentials together, we get 1.62, the net difference in places that Lawler has Clippers compared to other non-Clipper voters.

#### Step 3: For each year-award, standardize the summed place differentials.

We can use the differentials from step 2 as the ultimate measure of homerism, but this ignores the fact that the distributions for each year and award are not the same. Boxplots of total place differentials for all voters within each award are created:

<div class="figure" style="text-align: center">

<img src="/post/2018-11-13-nba-awards-voting-hometown-bias_files/figure-html/unnamed-chunk-4-1.png" alt="Grids are sorted by overall mean for each award (all years combined) from smallest to largest. Red points mark the means for each award. Note that all variables are skewed right, showing that voters with team affiliations generally place their own players higher on ballots compared to average." width="672" />
<p class="caption">
<span id="fig:unnamed-chunk-4"></span>Figure 1: Grids are sorted by overall mean for each award (all years combined) from smallest to largest. Red points mark the means for each award. Note that all variables are skewed right, showing that voters with team affiliations generally place their own players higher on ballots compared to average.
</p>

</div>

It is obvious that the means and standard deviations for each award are not the same, but there are some explanations for this. The three awards with the most slots on the ballost—All-NBA (15), All-Defense (10), and All-Rookie (10)—have the largest variances. The rest of the awards apart from MVP have only three slots and have most of their values near zero.

Rookie of the Year and All Rookie Team are the least susceptible to hometown bias relative to the other awards given their average values. For the two rookie awards, this can be explained by the fact that only a small pool of players are eligibile for the awards. A voter might not have to ability to make a homer vote for Rookie of the Year/All-Rookie Team even if they wanted to because their team did not have any rookies. Similarly to qualify for Sixth Man of the Year, players must have come off the bench for a certain proportion of games. For Coach of the Year, there are generally only about 30 candidates who qualify for the award and only three slots on the ballot. All-Defense and All-NBA, on the other hand, are crapshoots given that these awards have no requirements and have a large number of slots available. Add in the fact that even people who follow the NBA closely have trouble measuring good defense will present a great opportunity for homerism with All-Defense.

Even within each award, the means and standard deviations are not always consistent. Look at the Most Improved Player for 2013/14 compared to other years. There is much more variation in place differentials than other years. In this case, measure values of the same magnitude for different years should not have the same impact. For example, if an award has three slots and there are three established candidates in year one but only two worthy candidates in year two, a hometown vote in the year one should be more egregious than a hometown vote in the year two.

Standardizing the place differentials within each award and year combination should help with these issues. With z-scores, values from different awards and years can be compared. This is especially important because not every voter votes for every award.

#### Step 4: For each voter, take the mean of all their scores from each award.

We can summarize the results from step 3 to generate a final hometown bias (homer score) for every team-affiliated voter. We will do this using the mean of all of a voter’s scores for every award they vote in. Voters with the highest homer scores have the most hometown bias relative to all other team-affiliated voters. Voters with the lowest homer scores have the least (and possibly an anti-) hometown bias. Scores near zero imply average hometown bias relative to all team-affiliated voters. National media members without team affiliations do not have homer scores, but are used as part of the calculation for baseline player ballot positions in step 1.

## Hometown Bias Results

The homer scores for all 188 team-affiliated voters (out of 249 total voters) from 2013/14 to 2017/18 are presented in the table below, along with the number of awards they had ballots for (N). Scores are also broken down into two periods—when team broadcasters still voted (Pre: 2013/14, 2014/15, 2015/16) and when they did not (Post: 2016/17, 2017/18). Some voters have multiple team affilations, generally as the result of job changes over different seasons. Only the team affiliated with the voter for that season is used for the award scores for that same season.

    ## Warning: `funs()` was deprecated in dplyr 0.8.0.
    ## ℹ Please use a list of either functions or lambdas:
    ## 
    ## # Simple named list: list(mean = mean, median = median)
    ## 
    ## # Auto named with `tibble::lst()`: tibble::lst(mean, median)
    ## 
    ## # Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
    ## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
    ## generated.

<div class="datatables html-widget html-fill-item" id="htmlwidget-1" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"none","vertical":false,"data":[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188],["Tom Heinsohn","Bill Worrell","Al McCoy","Jason Lieser","Eric Reid","Ralph Lawler","Mike Ganter","Bob Fitzgerald","Eric Collins","Brian Davis","Diamond Leung","Brian Sieman","Tony Jones","Matt Pinto","Michael Smith","Mike Rice","Jim Barnett","Tim Roye","Jabari Young","Tim Reynolds","Dan Woike","Jason Kosmicki","Molly Sullivan","Manny Navarro","Ron Tillery","Jody Genessy","Michael Cage","Dell Curry","Cedric Maxwell","J Michael Falgoust","Bill Land","Tim Kempton","Steve Holman","Eddie Sefko","Jeff McDonald","Matt Velazquez","Keith Pompey","Mike Gorman","Michael Grange","Bob Rathbun","Scott Lauer","Adam Himmelsbach","Royce Young","Bill Wennington","Brian Wheeler","Rusty Simmons","Spero Dedes","Neil Funk","Greg Logan","Matt Bullard","Jose Paneda","Brian Scalabrine","Chris Denari","Eric Hasseltine","Steve Martin","Dominique Wilkins","Antonio Harvey","Tony Fiorentino","Gary Washburn","Stacey King","Sherrod Blakely","Ron Boone","Mike Monroe","Chris Marlowe","Joe Vardon","Paul Jones","Gina Mizell","Erik Horne","Will Guillory","Rod Boone","Jason Quick","Marc Zumoff","Stephanie Ready","Walt Frazier","Leo Rautins","Tom McGinnis","Sherman Hamilton","Clifton Brown","Aaron Falk","Jack Armstrong","Jackie MacMullan","Brett Dawson","Jeff Turner","Adrian Chavarria","Sam Smith","Anthony Slater","Mike Inglis","Rick Bonnell","Joe Freeman","Calvin Watkins","Baxter Holmes","Dwain Price","John Reid","Dennis Neumann","Joe Goodman","Scott Hastings","Rod Beard","Jason Jackson","Chuck Swirsky","Nick Friedell","Nate Taylor","Joe Cowley","Dave Johnson","Phil Chenier","Fred McLeod","Jonathan Feigen","Eddie Johnson","Paul Coro","Dante Marchitelli","Jason Lloyd","Ethan Skolnick","Bill Oram","David Wesley","Chris Dempsey","Charles Gardner","Mary Schmitt Boyer","Matt Devlin","Andre Aldridge","Gary Gerould","Bill Schoening","Doug Smith","Mark Followill","Sean Kelley","Elliott Teaford","Brian Lewis","Ted Davis","Ryan Wolstat","Pete Pranica","Jim Paschke","Mike Breen","K.C. Johnson","Craig Ackerman","Chris Haynes","Jason Jones","Dave McMenamin","Scott Bordow","Glenn Consor","Tim Bontemps","Joel Meyers","Jon Krawczynski","Sean Grande","Jim Petersen","David Mayo","Dei Lynam","Justin Verrier","John Denton","Ailene Voisin","Steve Buckhantz","Chuck Cooperstein","Ian Eagle","Grant Napear","Eric Smith","Vincent Goodwill","John Michael","Marc Berman","Brian Windhorst","Ira Winderman","Alan Horton","Mark Medina","Richard Walker","Stefan Bondy","Candace Buckner","Brian Mahoney","George Blaha","Mike Crispino","Vince Ellis","Malik Rose","Al Iannazzone","Steve Popper","Chase Hughes","Steve Albert","Mike Fratello","Chris Carrino","Tim Capstraw","Frank Isola","Andy Vasquez","Jessica Camerato","Peter Botte","Doug Haller","Jerry Zgoda","Bob Cooney","Brendan Brown","David Steele","Jim Spanarkel","Mark Boyle","Darnell Mayberry","Connor Letourneau","Michael Wallace"],["BOS","HOU","PHO","MIA","MIA","LAC","TOR","GSW","CHO","OKC","GSW","LAC","UTA","OKC","LAC","POR","GSW","GSW","POR","MIA","LAC","DEN","PHI","MIA","MEM","UTA","OKC","CHO","BOS","WAS","SAS","PHO","ATL","DAL","SAS","MIL","PHI","BOS","TOR","ATL","CHO","BOS","OKC","CHI","POR","GSW","NYK","CHI","BRK","HOU","MIA","BOS","IND","MEM","CHO","ATL","POR","MIA","BOS","CHI","BOS","UTA","SAS","DEN","CLE","TOR","DEN","OKC","NOP","BRK","POR","PHI","CHO","NYK","TOR","PHI","TOR","IND","UTA","TOR","national / BOS","OKC","ORL","HOU","CHI","OKC / GSW","MIA","CHO","POR","HOU","BOS","DAL","NOP","ORL","MIA","DEN","DET","MIA","CHI","CHI","IND","CHI","WAS","WAS","CLE","HOU","PHO","PHO","ORL","CLE","MIA","LAL / LAC","NOP","DEN","MIL","CLE","TOR","ATL","SAC","SAS","TOR","DAL","NOP","LAC","BRK","MIL","TOR","MEM","MIL","national / NYK","CHI","HOU","POR / CLE","SAC","LAL / CLE","PHO","WAS","BRK","NOP","MIN","BOS","MIN","DET","PHI","NOP","ORL","SAC","WAS","DAL","BRK","SAC","TOR","DET / CHI","CLE","NYK","national / MIA / CLE","MIA","MIN","LAL","CHO","BRK / NYK","IND","NYK","DET","NYK","DET","PHI","NYK","NYK","WAS","PHO","national / BRK","BRK","BRK","NYK","BRK","PHI","NYK","PHO","MIN","PHI","NYK","ORL","BRK","IND","OKC","GSW","MIA"],["TV color","TV play-by-play","radio play-by-play","writer","TV play-by-play","TV play-by-play","writer","TV play-by-play","TV play-by-play","TV play-by-play","writer","radio play-by-play","writer","radio play-by-play","TV color","TV color","TV color","radio play-by-play","writer","writer","writer","radio play-by-play","sideline reporter","writer","writer","writer","TV color","TV color","radio color","TV analyst/reporter","TV play-by-play","radio color","radio play-by-play","writer","writer","writer","writer","TV play-by-play","writer","TV play-by-play","radio play-by-play","writer","writer","radio color","radio play-by-play","writer","radio play-by-play","TV play-by-play","writer","TV color","radio play-by-play (Spanish)","TV color","TV play-by-play","radio play-by-play","TV play-by-play / radio play-by-play","TV color","radio color","TV color","writer","TV color","TV analyst/reporter","TV color","writer","TV play-by-play","writer","radio play-by-play","writer","writer","writer","writer","writer","TV play-by-play","sideline reporter / TV color","TV color","TV color","radio play-by-play","radio color","writer","writer","TV color","writer","writer","TV color","radio play-by-play (Spanish)","writer","writer","radio play-by-play","writer","writer","writer","writer","writer","writer","radio play-by-play","writer","TV color","writer","sideline reporter","radio play-by-play","writer","writer","writer","radio play-by-play","TV color","TV play-by-play","writer","TV color","writer","sideline reporter","writer","writer","writer","TV color","writer","writer","writer","TV play-by-play","sideline reporter","radio play-by-play","radio play-by-play","writer","TV play-by-play","radio play-by-play","writer","writer","radio play-by-play","writer","TV play-by-play","TV play-by-play","TV play-by-play","writer","radio play-by-play","writer","writer","writer","writer","radio color","writer","TV play-by-play","writer","radio play-by-play","TV color","writer","TV analyst/reporter","writer","writer","writer","TV play-by-play","radio play-by-play","TV play-by-play","TV play-by-play","radio play-by-play","writer","radio play-by-play","writer","writer","writer","radio play-by-play","writer","writer","writer","writer","writer","TV play-by-play","radio play-by-play","writer","TV color","writer","writer","writer","TV play-by-play","TV play-by-play","radio play-by-play","radio color","writer","writer","TV analyst/reporter","writer","writer","writer","writer","radio color","TV play-by-play","TV color","radio play-by-play","writer","writer","writer"],[12,13,9,4,9,20,9,15,4,20,16,20,18,18,20,21,15,17,7,27,21,20,4,18,45,27,5,12,14,9,27,22,27,39,45,9,39,12,18,27,5,5,23,12,7,17,3,10,9,13,9,4,27,27,19,9,13,10,45,12,33,27,27,20,9,11,9,9,9,8,15,12,15,10,9,7,6,9,27,8,18,9,15,13,27,36,8,26,30,12,5,20,18,17,8,20,25,10,11,10,13,19,19,21,21,27,14,27,11,32,15,43,8,21,36,9,9,18,27,27,36,21,27,9,14,27,9,27,27,45,30,12,17,45,27,9,20,8,27,18,14,27,22,13,9,17,18,21,14,12,27,11,28,6,30,45,12,27,27,18,21,23,27,23,7,22,4,12,13,9,4,18,12,11,40,13,6,4,9,45,14,11,15,4,27,15,9,3],[1.543655574952369,1.469853115137827,1.32793913679878,1.21331297759305,1.105825870373585,1.087290646513157,0.9145248208300448,0.8612504526601615,0.8539448205030828,0.8133638399279848,0.7854413738501206,0.7666185111534989,0.7147372885406149,0.6939480124550058,0.6283356424949295,0.6196985075901645,0.5996816780438645,0.5782486741484312,0.4959508755989917,0.4906712211423587,0.4660692422351772,0.4639479138175878,0.4614791116469859,0.4438083725207321,0.4414491029559353,0.4407585200784356,0.4226452599361569,0.4138991915322774,0.4133554100053894,0.332998051466274,0.3325624876063323,0.3320390891724896,0.3312353677169632,0.3292283520282401,0.3172451836487186,0.3046788271091707,0.2960392356527081,0.2759602588871093,0.2745668018145296,0.2706155756360685,0.2686456313987506,0.2570542519353,0.2508457871329689,0.2442280342900629,0.2303039738244476,0.2233774290412449,0.2220355600568823,0.1923702209385416,0.1729084645914293,0.154351414743924,0.1523446023216421,0.1514792211786438,0.145308418738438,0.1397474076482952,0.1360607143641916,0.1326195065968414,0.1315238802314579,0.1313808713345864,0.1293667341878521,0.1268470123561922,0.1219437209172194,0.1183853114448269,0.1096207248084819,0.1051685748529367,0.1005246383661125,0.1002143845255151,0.09926735673061016,0.09464080655762031,0.07951453998970652,0.07924412375558146,0.07674267291467801,0.07395672937541391,0.06180906500242481,0.06087541656253235,0.05593672112731619,0.04608030112836427,0.04301746243631092,0.03362218170024343,0.02335023763407702,0.0198043580492434,0.01683172117642067,0.01674949362270193,0.005433313286958426,0.00473072272130525,-0.007956171481792739,-0.01309299984995426,-0.02352313194317338,-0.0240468311468319,-0.02532552152629829,-0.05322820308686065,-0.05458160799405101,-0.05528624068951871,-0.06376115425492346,-0.07952655993057331,-0.08056579981680029,-0.08107427224840531,-0.08768156341454608,-0.09075487545369247,-0.09180957944628904,-0.09217425190487162,-0.0951872200606747,-0.1051878691705766,-0.1089146795676863,-0.1089971209237803,-0.1233019879295954,-0.1267198824150776,-0.1340835564708139,-0.1357697673965226,-0.1380733269342089,-0.1411592482132455,-0.1462747493815776,-0.1479665504972015,-0.1484057348881339,-0.1507355154567043,-0.1634754260735674,-0.1663150096858853,-0.1772203292412221,-0.1845119227001852,-0.1870978244422584,-0.1894265543739214,-0.1939107567616777,-0.1957736193231841,-0.1959096860291475,-0.1980138658891907,-0.1993361363530345,-0.2018776326059221,-0.2037379290010991,-0.210035507212554,-0.2113544574588634,-0.2218346252429942,-0.2301250378102478,-0.2306781165343643,-0.2308705607174366,-0.2323629620867159,-0.2333860925851971,-0.2338510678670095,-0.2431762545402597,-0.2468149522458939,-0.2475508381711859,-0.2491070359185699,-0.2496994347177688,-0.2545067137708157,-0.2548018548512855,-0.2551572659965964,-0.2582748003207901,-0.2603745738084075,-0.271312646260265,-0.2787520536091823,-0.2802987523892965,-0.2807556023258469,-0.2910514801447976,-0.2914788951010667,-0.2974151353139884,-0.3107001834511093,-0.3146165396174667,-0.3158333186418861,-0.3197424001896912,-0.3210177199555962,-0.3226518487022577,-0.3261992276134542,-0.3367902432804269,-0.346457150291781,-0.3479357470704318,-0.3498774655071245,-0.354390235060669,-0.3564305779453067,-0.3619604127876817,-0.3671829982763373,-0.3737654981365056,-0.3748473928314212,-0.377594997103382,-0.4110691193481696,-0.4131549005496284,-0.4136049450280347,-0.4230504641691678,-0.4277100713747825,-0.4352017558581553,-0.4442642849816315,-0.4467530823895253,-0.4615086219462224,-0.4733236486200298,-0.4759034847386752,-0.4791938681754361,-0.4814940656345794,-0.5155760422820482,-0.5335949876993175,-0.7795067970290566,-0.9561667005006492],[12,13,9,4,9,20,0,15,4,20,16,20,0,18,20,21,15,17,7,9,21,20,4,0,27,27,5,12,14,0,27,22,27,21,27,0,21,12,0,27,5,5,5,12,7,17,3,10,0,13,9,4,27,27,19,9,13,10,27,12,15,27,27,20,0,11,0,0,0,8,6,12,15,10,9,7,6,0,27,8,0,0,15,13,27,18,8,26,21,3,5,20,18,17,8,20,7,10,11,10,4,10,19,21,21,27,14,27,11,23,15,25,8,21,27,9,9,18,27,27,27,21,27,0,5,27,0,27,27,27,12,12,17,27,18,0,20,8,27,9,14,27,22,13,0,17,0,21,14,12,27,11,10,6,12,27,12,27,18,0,12,23,9,23,7,22,4,12,13,0,4,18,12,11,22,13,6,4,0,27,14,11,15,4,27,15,0,3],[1.543655574952369,1.469853115137827,1.32793913679878,1.21331297759305,1.105825870373585,1.087290646513157,null,0.8612504526601615,0.8539448205030828,0.8133638399279848,0.7854413738501206,0.7666185111534989,null,0.6939480124550058,0.6283356424949295,0.6196985075901645,0.5996816780438645,0.5782486741484312,0.4959508755989917,0.2626665664275618,0.4660692422351772,0.4639479138175878,0.4614791116469859,null,0.389677025572495,0.4407585200784356,0.4226452599361569,0.4138991915322774,0.4133554100053894,null,0.3325624876063323,0.3320390891724896,0.3312353677169632,-0.04229006300008761,0.2739200764734792,null,0.01353034670531512,0.2759602588871093,null,0.2706155756360685,0.2686456313987506,0.2570542519353,0.1603244916806915,0.2442280342900629,0.2303039738244476,0.2233774290412449,0.2220355600568823,0.1923702209385416,null,0.154351414743924,0.1523446023216421,0.1514792211786438,0.145308418738438,0.1397474076482952,0.1360607143641916,0.1326195065968414,0.1315238802314579,0.1313808713345864,0.1357599667403706,0.1268470123561922,-0.1417409639190629,0.1183853114448269,0.1096207248084819,0.1051685748529367,null,0.1002143845255151,null,null,null,0.07924412375558146,-0.0817158227267659,0.07395672937541391,0.06180906500242481,0.06087541656253235,0.05593672112731619,0.04608030112836427,0.04301746243631092,null,0.02335023763407702,0.0198043580492434,null,null,0.005433313286958426,0.00473072272130525,-0.007956171481792739,-0.3038898926267758,-0.02352313194317338,-0.0240468311468319,0.06534103440791682,-0.2852466579168824,-0.05458160799405101,-0.05528624068951871,-0.06376115425492346,-0.07952655993057331,-0.08056579981680029,-0.08107427224840531,0.2765031817766895,-0.09075487545369247,-0.09180957944628904,-0.09217425190487162,0.03315687686627244,0.07555412970277886,-0.1089146795676863,-0.1089971209237803,-0.1233019879295954,-0.1267198824150776,-0.1340835564708139,-0.1357697673965226,-0.1380733269342089,-0.1284501007226146,-0.1462747493815776,-0.195224188970183,-0.1484057348881339,-0.1507355154567043,-0.2768539067451918,-0.1663150096858853,-0.1772203292412221,-0.1845119227001852,-0.1870978244422584,-0.1894265543739214,-0.1444143147988371,-0.1957736193231841,-0.1959096860291475,null,-0.09750973265911503,-0.2018776326059221,null,-0.210035507212554,-0.2113544574588634,-0.171775722362493,-0.04795209954260587,-0.2306781165343643,-0.2308705607174366,-0.2063965059710165,-0.2632600485331447,null,-0.2431762545402597,-0.2468149522458939,-0.2475508381711859,-0.185909812482133,-0.2496994347177688,-0.2545067137708157,-0.2548018548512855,-0.2551572659965964,null,-0.2603745738084075,null,-0.2787520536091823,-0.2802987523892965,-0.2807556023258469,-0.2910514801447976,-0.2914788951010667,-0.5042927815819961,-0.3107001834511093,-0.1119191608729361,-0.3138529460436931,-0.3197424001896912,-0.3210177199555962,-0.3017070917735862,null,-0.3053134698457708,-0.346457150291781,-0.4014412144560163,-0.3498774655071245,-0.354390235060669,-0.3564305779453067,-0.3619604127876817,-0.3671829982763373,-0.3737654981365056,null,-0.377594997103382,-0.4110691193481696,-0.4131549005496284,-0.4136049450280347,-0.4012069231235429,-0.4277100713747825,-0.4352017558581553,-0.4442642849816315,null,-0.4497637590998681,-0.4733236486200298,-0.4759034847386752,-0.4791938681754361,-0.4814940656345794,-0.5155760422820482,-0.5335949876993175,null,-0.9561667005006492],[0,0,0,0,0,0,9,0,0,0,0,0,18,0,0,0,0,0,0,18,0,0,0,18,18,0,0,0,0,9,0,0,0,18,18,9,18,0,18,0,0,0,18,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,18,0,18,0,0,0,9,0,9,9,9,0,9,0,0,0,0,0,0,9,0,0,18,9,0,0,0,18,0,0,9,9,0,0,0,0,0,0,18,0,0,0,9,9,0,0,0,0,0,0,0,9,0,18,0,0,9,0,0,0,0,0,9,0,0,9,9,0,9,0,0,18,18,0,0,18,9,9,0,0,0,9,0,0,0,0,9,0,18,0,0,0,0,0,18,0,18,18,0,0,9,18,9,0,18,0,0,0,0,0,0,9,0,0,0,0,18,0,0,0,9,18,0,0,0,0,0,0,9,0],[null,null,null,null,null,null,0.9145248208300448,null,null,null,null,null,0.7147372885406149,null,null,null,null,null,null,0.6046735484997571,null,null,null,0.4438083725207321,0.5191072190310958,null,null,null,null,0.332998051466274,null,null,null,0.7626665028946223,0.3822328444115776,0.3046788271091707,0.6256329394246667,null,0.2745668018145296,null,null,null,0.2759905914252682,null,null,null,null,null,0.1729084645914293,null,null,null,null,null,null,null,null,null,0.1197768853590742,null,0.3416809582807878,null,null,null,0.1005246383661125,null,0.09926735673061016,0.09464080655762031,0.07951453998970652,null,0.1823816700089739,null,null,null,null,null,null,0.03362218170024343,null,null,0.01683172117642067,0.01674949362270193,null,null,null,0.2777038929268673,null,null,-0.2368808187061336,0.02411128185647993,null,null,null,null,null,null,-0.2293089643222488,null,null,null,-0.1522290409170957,-0.3060123123631938,null,null,null,null,null,null,null,-0.1736381806893021,null,-0.08233094150694925,null,null,0.1766600159413055,null,null,null,null,null,-0.3424000826501993,null,null,-0.1980138658891907,-0.2559063606274343,null,-0.2037379290010991,null,null,-0.296922979563746,-0.3515736633220091,null,null,-0.271312646260265,-0.1736381806893021,-0.2338510678670095,null,null,null,-0.3123042593550067,null,null,null,null,-0.2582748003207901,null,-0.271312646260265,null,null,null,null,null,-0.1824831096095397,null,-0.4497481254471538,-0.3188038775391758,null,null,-0.3645413625596007,-0.3261992276134542,-0.378759274526635,null,-0.3211830133776394,null,null,null,null,null,null,-0.3748473928314212,null,null,null,null,-0.4497481254471538,null,null,null,-0.4467530823895253,-0.479125916215754,null,null,null,null,null,null,-0.7795067970290566,null]],"container":"<table class=\"cell-border nowrap\">\n  <thead>\n    <tr>\n      <th>Rank<\/th>\n      <th>Voter<\/th>\n      <th>Team<\/th>\n      <th>Role<\/th>\n      <th>N<\/th>\n      <th>Score<\/th>\n      <th>Pre N<\/th>\n      <th>Pre Score<\/th>\n      <th>Post N<\/th>\n      <th>Post Score<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"lftp","scrollX":true,"columnDefs":[{"targets":5,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \",\", \".\", null);\n  }"},{"targets":7,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \",\", \".\", null);\n  }"},{"targets":9,"render":"function(data, type, row, meta) {\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \",\", \".\", null);\n  }"},{"className":"dt-right","targets":[0,4,5,6,7,8,9]},{"name":"Rank","targets":0},{"name":"Voter","targets":1},{"name":"Team","targets":2},{"name":"Role","targets":3},{"name":"N","targets":4},{"name":"Score","targets":5},{"name":"Pre N","targets":6},{"name":"Pre Score","targets":7},{"name":"Post N","targets":8},{"name":"Post Score","targets":9}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":["options.columnDefs.0.render","options.columnDefs.1.render","options.columnDefs.2.render"],"jsHooks":[]}</script>

Some observations from the results:

- About half of team-affiliated media are broadcasters and the other half are beat writers (with a few sideline reporters and TV analysts making up the remainder). Announcers, who stopped receiving ballots starting 2016/17, had an average score of 0.1, versus writers, who had an average of -0.06. This stronger bias among announcers can be seen at the top of list, as 14 of the top 20 voters with the highest homer scores are announcers.

- It is most fitting that the two voters finishing with the highest hometown bias scores, Boston’s Tommy Heinsohn and Houston’s Bill Worrell, are notorious for being among the biggest homers of all local broadcasters. We will take a closer look at their offending ballots later on.

- Nearly all the broadcasters in the top 10 have been calling games for their respective teams for over 20 years (the exceptions being Eric Collins and Brian Davis).

- As a Los Angeles native who has watched many Clipper games, I was surprised to see Ralph Lawler finish so high, given that he was never as extreme in his homerism as some of his peers.

- Voters with multiple team affiliations or that also have a national role generally finished with lower hometown bias scores than single team media. Jackie MacMullan has the highest score in this group of 10 and has a rank of 81.

- There is little difference in score between TV play-by-play announcers and TV color commentators.

- We can summarize the results by team to see which franchises have the most biased groups of voters. Voters associated with multiple teams are excluded. The mean score for all voters is indicated by the thick gray horizontal line near 0:

<div class="plotly html-widget html-fill-item" id="htmlwidget-2" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-2">{"x":{"data":[{"x":[0.44999999999999996,12.550000000000001],"y":[0.019059935806435571,0.019059935806435571],"text":"","type":"scatter","mode":"lines","line":{"width":7.559055118110237,"color":"rgba(179,179,179,1)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[6,4,6],"y":[-0.13906461227907907,0.3243078394244886,-0.13028157500100929],"text":["NOP","UTA","WAS"],"hovertext":["Will Guillory: 0.08<br />John Reid: -0.06<br />David Wesley: -0.15<br />Sean Kelley: -0.2<br />Joel Meyers: -0.25<br />Justin Verrier: -0.26","Tony Jones: 0.71<br />Jody Genessy: 0.44<br />Ron Boone: 0.12<br />Aaron Falk: 0.02","J Michael Falgoust: 0.33<br />Dave Johnson: -0.11<br />Phil Chenier: -0.11<br />Glenn Consor: -0.24<br />Steve Buckhantz: -0.28<br />Chase Hughes: -0.37"],"textfont":{"size":[16.520312361510083,13.648497030559248,16.520312361510083],"color":"rgba(0,43,92,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#002B5C","legendgroup":"#002B5C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4],"y":[-0.068007172257295551],"text":"MIL","hovertext":"Matt Velazquez: 0.3<br />Charles Gardner: -0.16<br />Ted Davis: -0.2<br />Jim Paschke: -0.21","textfont":{"size":13.648497030559248,"color":"rgba(0,71,27,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#00471B","legendgroup":"#00471B","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4],"y":[-0.32153502289780106],"text":"MIN","hovertext":"Jon Krawczynski: -0.25<br />Jim Petersen: -0.25<br />Alan Horton: -0.32<br />Jerry Zgoda: -0.46","textfont":{"size":13.648497030559248,"color":"rgba(0,80,131,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#005083","legendgroup":"#005083","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[11],"y":[-0.27636662733404221],"text":"NYK","hovertext":"Spero Dedes: 0.22<br />Walt Frazier: 0.06<br />Mike Breen: -0.22<br />Marc Berman: -0.31<br />Brian Mahoney: -0.35<br />Mike Crispino: -0.35<br />Al Iannazzone: -0.37<br />Steve Popper: -0.37<br />Frank Isola: -0.42<br />Peter Botte: -0.44<br />Brendan Brown: -0.48","textfont":{"size":21.797718221963954,"color":"rgba(0,107,182,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#006BB6","legendgroup":"#006BB6","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[7],"y":[0.25122831599044587],"text":"OKC","hovertext":"Brian Davis: 0.81<br />Matt Pinto: 0.69<br />Michael Cage: 0.42<br />Royce Young: 0.25<br />Erik Horne: 0.09<br />Brett Dawson: 0.02<br />Darnell Mayberry: -0.53","textfont":{"size":17.736358032302295,"color":"rgba(0,125,195,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#007DC3","legendgroup":"#007DC3","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4,5],"y":[-0.050532565093439799,-0.19034700311233349],"text":["DAL","ORL"],"hovertext":["Eddie Sefko: 0.33<br />Dwain Price: -0.06<br />Mark Followill: -0.2<br />Chuck Cooperstein: -0.28","Jeff Turner: 0.01<br />Dennis Neumann: -0.08<br />Dante Marchitelli: -0.14<br />John Denton: -0.26<br />David Steele: -0.48"],"textfont":{"size":[13.648497030559248,15.175231921049336],"color":"rgba(0,125,197,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#007DC5","legendgroup":"#007DC5","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[10],"y":[0.26053658505284844],"text":"BOS","hovertext":"Tom Heinsohn: 1.54<br />Cedric Maxwell: 0.41<br />Mike Gorman: 0.28<br />Adam Himmelsbach: 0.26<br />Brian Scalabrine: 0.15<br />Gary Washburn: 0.13<br />Sherrod Blakely: 0.12<br />Jackie MacMullan: 0.02<br />Baxter Holmes: -0.05<br />Sean Grande: -0.25","textfont":{"size":20.873084102046445,"color":"rgba(0,131,72,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#008348","legendgroup":"#008348","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[10],"y":[-0.26217872045129592],"text":"BRK","hovertext":"Greg Logan: 0.17<br />Rod Boone: 0.08<br />Brian Lewis: -0.2<br />Tim Bontemps: -0.25<br />Ian Eagle: -0.28<br />Mike Fratello: -0.41<br />Chris Carrino: -0.41<br />Tim Capstraw: -0.41<br />Andy Vasquez: -0.43<br />Jim Spanarkel: -0.48","textfont":{"size":20.873084102046445,"color":"rgba(6,25,34,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#061922","legendgroup":"#061922","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[3],"y":[0.12372033446389216],"text":"MEM","hovertext":"Ron Tillery: 0.44<br />Eric Hasseltine: 0.14<br />Pete Pranica: -0.21","textfont":{"size":11.837507389818349,"color":"rgba(15,88,108,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#0F586C","legendgroup":"#0F586C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[7],"y":[0.19773048057720588],"text":"CHO","hovertext":"Eric Collins: 0.85<br />Dell Curry: 0.41<br />Scott Lauer: 0.27<br />Steve Martin: 0.14<br />Stephanie Ready: 0.06<br />Rick Bonnell: -0.02<br />Richard Walker: -0.33","textfont":{"size":17.736358032302295,"color":"rgba(29,17,96,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#1D1160","legendgroup":"#1D1160","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[5],"y":[0.08731481153920502],"text":"DEN","hovertext":"Jason Kosmicki: 0.46<br />Chris Marlowe: 0.11<br />Gina Mizell: 0.1<br />Scott Hastings: -0.08<br />Chris Dempsey: -0.15","textfont":{"size":15.175231921049336,"color":"rgba(77,144,205,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#4D90CD","legendgroup":"#4D90CD","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4],"y":[-0.24545622823350921],"text":"SAC","hovertext":"Gary Gerould: -0.19<br />Jason Jones: -0.23<br />Ailene Voisin: -0.27<br />Grant Napear: -0.29","textfont":{"size":13.648497030559248,"color":"rgba(114,76,159,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#724C9F","legendgroup":"#724C9F","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[5],"y":[-0.1281903581827446],"text":"CLE","hovertext":"Joe Vardon: 0.1<br />Fred McLeod: -0.12<br />Jason Lloyd: -0.14<br />Mary Schmitt Boyer: -0.17<br />John Michael: -0.31","textfont":{"size":15.175231921049336,"color":"rgba(134,0,56,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#860038","legendgroup":"#860038","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[12],"y":[0.16002635483336414],"text":"MIA","hovertext":"Jason Lieser: 1.21<br />Eric Reid: 1.11<br />Tim Reynolds: 0.49<br />Manny Navarro: 0.44<br />Jose Paneda: 0.15<br />Tony Fiorentino: 0.13<br />Mike Inglis: -0.02<br />Joe Goodman: -0.08<br />Jason Jackson: -0.09<br />Ethan Skolnick: -0.15<br />Ira Winderman: -0.32<br />Michael Wallace: -0.96","textfont":{"size":22.677165354330711,"color":"rgba(152,0,46,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#98002E","legendgroup":"#98002E","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4],"y":[0.14250046042240283],"text":"SAS","hovertext":"Bill Land: 0.33<br />Jeff McDonald: 0.32<br />Mike Monroe: 0.11<br />Bill Schoening: -0.19","textfont":{"size":13.648497030559248,"color":"rgba(186,195,201,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#BAC3C9","legendgroup":"#BAC3C9","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[8,6,10],"y":[0.0045240447213773516,0.20305150842779232,0.054171663867789432],"text":["CHI","HOU","TOR"],"hovertext":["Bill Wennington: 0.24<br />Neil Funk: 0.19<br />Stacey King: 0.13<br />Sam Smith: -0.01<br />Chuck Swirsky: -0.09<br />Nick Friedell: -0.09<br />Joe Cowley: -0.11<br />K.C. Johnson: -0.23","Bill Worrell: 1.47<br />Matt Bullard: 0.15<br />Adrian Chavarria: 0<br />Calvin Watkins: -0.05<br />Jonathan Feigen: -0.13<br />Craig Ackerman: -0.23","Mike Ganter: 0.91<br />Michael Grange: 0.27<br />Paul Jones: 0.1<br />Leo Rautins: 0.06<br />Sherman Hamilton: 0.04<br />Jack Armstrong: 0.02<br />Matt Devlin: -0.18<br />Doug Smith: -0.19<br />Ryan Wolstat: -0.2<br />Eric Smith: -0.29"],"textfont":{"size":[18.854627437180454,16.520312361510083,20.873084102046445],"color":"rgba(206,17,65,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#CE1141","legendgroup":"#CE1141","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[6],"y":[0.2548157314389069],"text":"POR","hovertext":"Mike Rice: 0.62<br />Jabari Young: 0.5<br />Brian Wheeler: 0.23<br />Antonio Harvey: 0.13<br />Jason Quick: 0.08<br />Joe Freeman: -0.03","textfont":{"size":16.520312361510083,"color":"rgba(224,58,62,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#E03A3E","legendgroup":"#E03A3E","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4],"y":[0.13748963181242196],"text":"ATL","hovertext":"Steve Holman: 0.33<br />Bob Rathbun: 0.27<br />Dominique Wilkins: 0.13<br />Andre Aldridge: -0.18","textfont":{"size":13.648497030559248,"color":"rgba(225,58,62,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#E13A3E","legendgroup":"#E13A3E","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[7],"y":[0.047417964963430842],"text":"PHO","hovertext":"Al McCoy: 1.33<br />Tim Kempton: 0.33<br />Eddie Johnson: -0.13<br />Paul Coro: -0.14<br />Scott Bordow: -0.23<br />Steve Albert: -0.38<br />Doug Haller: -0.45","textfont":{"size":17.736358032302295,"color":"rgba(229,96,32,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#E56020","legendgroup":"#E56020","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4,5,8],"y":[-0.26219786542956569,0.55006003530151426,-0.081010963182373885],"text":["DET","LAC","PHI"],"hovertext":["Rod Beard: -0.09<br />David Mayo: -0.25<br />George Blaha: -0.35<br />Vince Ellis: -0.36","Ralph Lawler: 1.09<br />Brian Sieman: 0.77<br />Michael Smith: 0.63<br />Dan Woike: 0.47<br />Elliott Teaford: -0.2","Molly Sullivan: 0.46<br />Keith Pompey: 0.3<br />Marc Zumoff: 0.07<br />Tom McGinnis: 0.05<br />Dei Lynam: -0.26<br />Malik Rose: -0.36<br />Jessica Camerato: -0.44<br />Bob Cooney: -0.47"],"textfont":{"size":[13.648497030559248,15.175231921049336,18.854627437180454],"color":"rgba(237,23,76,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#ED174C","legendgroup":"#ED174C","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[6,1],"y":[0.37808213511912769,-0.32265184870225766],"text":["GSW","LAL"],"hovertext":["Bob Fitzgerald: 0.86<br />Diamond Leung: 0.79<br />Jim Barnett: 0.6<br />Tim Roye: 0.58<br />Rusty Simmons: 0.22<br />Connor Letourneau: -0.78","Mark Medina: -0.32"],"textfont":{"size":[16.520312361510083,3.7795275590551185],"color":"rgba(253,185,39,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#FDB927","legendgroup":"#FDB927","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[5],"y":[-0.15565796243916449],"text":"IND","hovertext":"Chris Denari: 0.15<br />Clifton Brown: 0.03<br />Nate Taylor: -0.1<br />Candace Buckner: -0.35<br />Mark Boyle: -0.52","textfont":{"size":15.175231921049336,"color":"rgba(255,198,51,1)"},"type":"scatter","mode":"text","hoveron":"points","name":"#FFC633","legendgroup":"#FFC633","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283108,"r":7.3059360730593621,"b":40.182648401826498,"l":48.949771689497723},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.44999999999999996,12.550000000000001],"tickmode":"array","ticktext":["2","4","6","8","10","12"],"tickvals":[2,4,6,8,10,12],"categoryorder":"array","categoryarray":["2","4","6","8","10","12"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Number of Voters","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.36628744290244625,0.59369562950170285],"tickmode":"array","ticktext":["-0.2","0.0","0.2","0.4"],"tickvals":[-0.20000000000000001,0,0.20000000000000001,0.39999999999999997],"categoryorder":"array","categoryarray":["-0.2","0.0","0.2","0.4"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Mean Score","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5aa968ef3d3d":{"yintercept":{},"type":"scatter"},"5aa9329da59d":{"x":{},"y":{},"text":{},"label":{},"size":{},"colour":{}}},"cur_data":"5aa968ef3d3d","visdat":{"5aa968ef3d3d":["function (y) ","x"],"5aa9329da59d":["function (y) ","x"]},".hideLegend":true,"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>

The average hometown score of all Boston Celtics voters is the highest of any team with at least 10 voters. The two New York teams each have large voting blocs, but unfortunately for the Knicks and Nets, tend not to vote for their own players. The Clippers’ five voters average the higher homer scores of any team. The Los Angeles Lakers, barely visible in the bottom left corner, have had only one voter these last five years. Bill Oram and Dave McMenamin are Laker beat writers, but were excluded because of multiple team affiliations.

## Detailed Ballots

We will take a closer look at some of the more interesting voters and ballots. These votes will be presented together with the actual result totals for the awards from all voters.

    ## `summarise()` has grouped output by 'year', 'award', 'value'. You can override
    ## using the `.groups` argument.

### Tommy Heinsohn

Topping the hometown bias list is Tommy Heinsohn. Heinsohn had a nine year career playing with the Boston Celtics from 1956 to 1965, winning six championships alongside Bill Russell, but is now the TV color commentator for those same Celtics. Heinsohn took part in 12 awards from 2013/14 to 2015/16, about half of which contributed to his high homer score.

#### 14/15 Improved

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Tyler Zeller
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.98
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Rudy Gobert
</td>
<td style="text-align:left;">
UTA
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
2.97
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Khris Middleton
</td>
<td style="text-align:left;">
MIL
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3.97
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Jimmy Butler
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
328
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
121
</td>
<td style="text-align:right;">
1.46
</td>
<td style="text-align:right;">
92
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
135
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
2.95
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Rudy Gobert
</td>
<td style="text-align:left;">
UTA
</td>
<td style="text-align:right;">
133
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
2.97
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Hassan Whiteside
</td>
<td style="text-align:left;">
MIA
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
3.49
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Klay Thompson
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
3.77
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
11
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Tyler Zeller
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.98
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
15
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Jae Crowder
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.98
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
</tbody>
</table>

#### 14/15 Coach

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Mike Budenholzer
</td>
<td style="text-align:left;">
ATL
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Brad Stevens
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
34
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.68
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
4
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
28
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Jason Kidd
</td>
<td style="text-align:left;">
MIL
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
3.62
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Mike Budenholzer
</td>
<td style="text-align:left;">
ATL
</td>
<td style="text-align:right;">
321
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
58
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Steve Kerr
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
298
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1.71
</td>
<td style="text-align:right;">
56
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Jason Kidd
</td>
<td style="text-align:left;">
MIL
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
3.62
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Brad Stevens
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
42
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
34
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.68
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
4
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
28
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Gregg Popovich
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
3.75
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>

#### 15/16 Coach

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Brad Stevens
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
34
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.58
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
5
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
10
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
19
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Steve Kerr
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
89
</td>
<td style="text-align:right;">
2.19
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Dwane Casey
</td>
<td style="text-align:left;">
TOR
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
3.55
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Steve Kerr
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
235
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
89
</td>
<td style="text-align:right;">
2.19
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Terry Stotts
</td>
<td style="text-align:left;">
POR
</td>
<td style="text-align:right;">
223
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
111
</td>
<td style="text-align:right;">
2.28
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Gregg Popovich
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
114
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
3.12
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Steve Clifford
</td>
<td style="text-align:left;">
CHO
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
3.48
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Dwane Casey
</td>
<td style="text-align:left;">
TOR
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
3.55
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
6
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Brad Stevens
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
54
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
34
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3.58
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
5
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
10
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
19
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
</tbody>
</table>

### 

Among Heinsohn’s 12 ballots, his picks for 2014/15 Most Improved Player scored the highest for hometown bias. Out of the 129 ballots for 2014/15 Most Improved Player, Heinsohn was the only participant to give Tyler Zeller a vote, placing the Celtic big man at the very top of his ballot. He ignored Jimmy Butler, who was mentioned by over 90% of other voters. He did resist mentioning Jae Crowder, who received a single second place vote (from Celtic radio color man Cedric Maxwell in another homer pick).

The 2014/15 and 2015/16 ballots for Coach of the Year were Heinsohn’s second and third most homer selections, respectively. The announcer placed Celtics coach Brad Stevens second in 2014/15 (finished just outside the top three overall and received only six first or second place votes) and first in 2015/16 (finished sixth overall with only five first place votes). Heinsohn was only 1 of 5 voters to leave Golden State coach Steve Kerr off their 2014/15 Coach ballot and only 1 of 19 voters to leave Portland coach Terry Stotts off their 2015/16 Coach ballot. The 2014/15 vote had a higher homer score than the 2015/16 vote because of the greater variation in average places among vote-getters in 2015/16.

### Bill Worrell

Finishing just behind Tommy Heinsohn in hometown bias score is Bill Worrell, the Houston Rockets’ TV play-by-play announcer for over 30 years. Of Worrell’s 13 ballots over a 3 year period, 9 contributed positively to his homer score.

#### 13/14 MVP

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kevin Durant
</td>
<td style="text-align:left;">
OKC
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
MIA
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
James Harden
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
125
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
37
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
5.51
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
7
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
10
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
20
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Joakim Noah
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:right;">
4.34
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Kevin Love
</td>
<td style="text-align:left;">
MIN
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
5.86
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
6
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kevin Durant
</td>
<td style="text-align:left;">
OKC
</td>
<td style="text-align:right;">
619
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1.05
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
MIA
</td>
<td style="text-align:right;">
505
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Blake Griffin
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
269
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
104
</td>
<td style="text-align:right;">
3.85
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Joakim Noah
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
208
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:right;">
4.34
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
5
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
James Harden
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
61
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
125
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
37
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
5.51
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
7
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
10
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
20
</td>
</tr>
</tbody>
</table>

#### 15/16 MVP

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Stephen Curry
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Russell Westbrook
</td>
<td style="text-align:left;">
OKC
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
108
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
James Harden
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
131
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
5.95
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
CLE
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
3.09
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Chris Paul
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:right;">
5.39
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
37
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Stephen Curry
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
655
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
CLE
</td>
<td style="text-align:right;">
381
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
3.09
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Kawhi Leonard
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
378
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
3.11
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
54
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Russell Westbrook
</td>
<td style="text-align:left;">
OKC
</td>
<td style="text-align:right;">
297
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
108
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Kevin Durant
</td>
<td style="text-align:left;">
OKC
</td>
<td style="text-align:right;">
105
</td>
<td style="text-align:right;">
131
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
5.20
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
9
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
James Harden
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
6
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
131
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
5.95
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
</tr>
</tbody>
</table>

### 

Worrell’s two most biased award ballots were for 2013/14 MVP and 2015/16 MVP, both cases where he placed Rocket guard James Harden third. There was a solid consensus for the 2013/14 MVP, with Kevin Durant first, LeBron James second, and Blake Griffin or Joakim Noah third and fourth. Worrell broke this consensus, placing Rocket guard James Harden third on his ballot for MVP ahead of Blake Griffin (who was mentioned by 83% of voters and finished 3rd overall, but was left off of Worrell’s ballot completely) and Joakim Noah (appeared on more than twice as many ballots as Harden).

Comparing Bill Worrell’s 2015/16 MVP ballot to his 2013/14 MVP ballot above highlights a case where the homer score gives a result that is unanticpated. From looking at the two MVP ballots, it is expected that Worrell’s third place vote for Harden in 2015/16 (where the Houston star received only three mentions with Worrell providing the highest placement of any voter) should have generated a higher homer score than the third place vote for Harden in 2013/14 (where there were 37 mentions for the Rocket guard). This is a consequence of using standardized instead of raw scores in calculating values. Score may be scaled up or down because of the mean and variance of all scores for a particualar award.

#### 14/15 Defensive

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:right;">
2.43
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
Trevor Ariza
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3.98
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
2.67
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kawhi Leonard
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
218
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
2.31
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
202
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:right;">
2.43
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
172
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
2.67
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Anthony Davis
</td>
<td style="text-align:left;">
NOP
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Andrew Bogut
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
3.81
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Rudy Gobert
</td>
<td style="text-align:left;">
UTA
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
3.81
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
14
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
Trevor Ariza
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3.98
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
15
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
Patrick Beverley
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3.99
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
</tr>
</tbody>
</table>

#### 15/16 Defensive

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
121
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Anthony Davis
</td>
<td style="text-align:left;">
NOP
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
3.98
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
Trevor Ariza
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3.99
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kawhi Leonard
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
338
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
84
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
271
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
121
</td>
<td style="text-align:right;">
1.92
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Hassan Whiteside
</td>
<td style="text-align:left;">
MIA
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:right;">
3.48
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
3.67
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Paul Millsap
</td>
<td style="text-align:left;">
ATL
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3.86
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
13
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
Trevor Ariza
</td>
<td style="text-align:left;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
HOU
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
3.99
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(206, 17, 65, 255) !important;background-color: rgba(196, 206, 211, 255) !important;">
</td>
</tr>
</tbody>
</table>

### 

Some more interesting Worrell results came from two ballots that had lower homertown bias values than the MVP ballots. The Spurs’ Kawhi Leonard won the 2015/16 Defensive Player of the Year Award in almost unanimous fashion, being mentioned on 129 out of 130 ballots. The only media member to not have voted for Leonard was Worrell, with a ballot that included spots for Anthony Davis (only two mentions) and Rocket Trevor Ariza (his sole mention). Worrell claimed this oversight was because of an [error](https://www.mysanantonio.com/sports/spurs/article/The-mystery-of-Kawhi-Leonard-s-missing-Defensive-7291371.php) and that he meant to vote Leonard first, but there was a similar situation with the previous year’s Defensive Player of the Year award. Leonard also won the 2014/15 award, appearing on 80% of ballots (103 out of 129). Worrell again left the Spur off his ballot, instead giving Trevor Ariza his only vote (again). If we go back to Worrell’s 2015/16 MVP ballot above, we see a third instance where he completely ignored Leonard. Leonard finished third and was mentioned by 93% of all voters.

### Darnell Mayberry

On the opposite end of the homer spectrum are media members who tend to place their own players lower than average or leave them off their ballots altogether. Of voters that have participated in at least 10 awards, Darnell Mayberry has the lowest homer score (although there is little separation between him and many of his peers at the bottom of the list). Mayberry covered the Oklahoma City Thunder from 2005 to 2015, over which he was involved in a few [incidents](https://www.welcometoloudcity.com/2014/1/10/5294586/kd-smokes-perk-calls-out-darnell-mayberry-on-twitter) with players (but so did many other [media](http://grantland.com/the-triangle/nba-russell-westbrook-kevin-durant-oklahoma-city-thunder-sports-media/) with the Thunder). We will review a few of his most anti-homer ballots.

#### 14/15 MVP

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
James Harden
</td>
<td style="text-align:left;">
HOU
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Stephen Curry
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
1.28
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
CLE
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
3.42
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Chris Paul
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
54
</td>
<td style="text-align:right;">
5.32
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
29
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Anthony Davis
</td>
<td style="text-align:left;">
NOP
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
97
</td>
<td style="text-align:right;">
4.85
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
53
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Stephen Curry
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
614
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
1.28
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
James Harden
</td>
<td style="text-align:left;">
HOU
</td>
<td style="text-align:right;">
520
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
LeBron James
</td>
<td style="text-align:left;">
CLE
</td>
<td style="text-align:right;">
335
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
3.42
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
Russell Westbrook
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
OKC
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
230
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
108
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
4.23
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
5
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
33
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
41
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
29
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Anthony Davis
</td>
<td style="text-align:left;">
NOP
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
97
</td>
<td style="text-align:right;">
4.85
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
53
</td>
</tr>
</tbody>
</table>

#### 14/15 All Defense

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
1.22
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kawhi Leonard
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
126
</td>
<td style="text-align:right;">
1.12
</td>
<td style="text-align:right;">
116
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Andrew Bogut
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
2.21
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Jimmy Butler
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
1.98
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Avery Bradley
</td>
<td style="text-align:left;">
BOS
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
2.80
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
DeMarre Carroll
</td>
<td style="text-align:left;">
ATL
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
2.91
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Anthony Davis
</td>
<td style="text-align:left;">
NOP
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
108
</td>
<td style="text-align:right;">
1.80
</td>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
84
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Tony Allen
</td>
<td style="text-align:left;">
MEM
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Chris Paul
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Kawhi Leonard
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
242
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
126
</td>
<td style="text-align:right;">
1.12
</td>
<td style="text-align:right;">
116
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Draymond Green
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
229
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
1.22
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Tony Allen
</td>
<td style="text-align:left;">
MEM
</td>
<td style="text-align:right;">
207
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
119
</td>
<td style="text-align:right;">
1.40
</td>
<td style="text-align:right;">
88
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
DeAndre Jordan
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
187
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
1.55
</td>
<td style="text-align:right;">
84
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Chris Paul
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
170
</td>
<td style="text-align:right;">
129
</td>
<td style="text-align:right;">
103
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
67
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
13
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
Russell Westbrook
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
OKC
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
35
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
22
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
2.73
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
13
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
9
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
24
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
Serge Ibaka
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
OKC
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
8
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
129
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
8
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
2.94
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
8
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
</tr>
</tbody>
</table>

#### 13/14 Sixth Man

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Jamal Crawford
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
111
</td>
<td style="text-align:right;">
1.87
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Markieff Morris
</td>
<td style="text-align:left;">
PHO
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
3.48
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Taj Gibson
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
109
</td>
<td style="text-align:right;">
1.98
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Jamal Crawford
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
266
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
111
</td>
<td style="text-align:right;">
1.87
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Taj Gibson
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
252
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
109
</td>
<td style="text-align:right;">
1.98
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Manu Ginobili
</td>
<td style="text-align:left;">
SAS
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
3.20
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Markieff Morris
</td>
<td style="text-align:left;">
PHO
</td>
<td style="text-align:right;">
65
</td>
<td style="text-align:right;">
125
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
3.48
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
5
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
Reggie Jackson
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
OKC
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
37
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
125
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
25
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
3.70
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
4
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
4
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
17
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 125, 195, 255) !important;background-color: rgba(240, 81, 51, 255) !important;">
</td>
</tr>
</tbody>
</table>

### 

Of Mayberry’s 15 ballots, his 2014/15 MVP vote has the lowest hometown bias score. Russell Westbrook appeared on 83% of ballots and finished fourth in MVP voting in a season where he led the Oklahoma City Thunder to a 45-37 record (barely missing the playoffs) after Kevin Durant went down with a season-ending injury. Mayberry left Westbrook completely off of his MVP ballot, preferring Chris Paul and Anthony Davis. While Davis finished fifth in voting and garnered nearly a hundred mentions, Paul was mentioned on only half as many ballots as Westbrook.

Mayberry again left Westbrook, who was mentioned by 17% of voters, off of his 2014/15 All-Defense ballot. Also for the same award, he ignored Thunder center Serge Ibaka who was mentioned on 6% of ballots. For 2013/14 Sixth Man of the Year, Mayberry left off Thunder guard Reggie Jackson, who appeared on 20% of ballots and finished fifth overall. These are minor snubs, but taken together, do enough to generate an aggregate score that puts Mayberry at the bottom of the homer list.

### Most Homer Ballots

Here are the individual ballots with the three highest hometown bias scores. The voters themselves do not necessarily have the highest aggregate homer scores.

#### Ron Boone (UTA) 13/14 Rookie

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
Trey Burke
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
UTA
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
124
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
66
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
3.35
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
13
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
52
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Michael Carter-Williams
</td>
<td style="text-align:left;">
PHI
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
1.21
</td>
<td style="text-align:right;">
104
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Victor Oladipo
</td>
<td style="text-align:left;">
ORL
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
2.04
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
89
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Michael Carter-Williams
</td>
<td style="text-align:left;">
PHI
</td>
<td style="text-align:right;">
346
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
1.21
</td>
<td style="text-align:right;">
104
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Victor Oladipo
</td>
<td style="text-align:left;">
ORL
</td>
<td style="text-align:right;">
243
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
2.04
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
89
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
Trey Burke
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
UTA
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
81
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
124
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
66
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
3.35
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
13
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
52
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 43, 92, 255) !important;background-color: rgba(249, 160, 27, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Mason Plumlee
</td>
<td style="text-align:left;">
BRK
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
3.60
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Tim Hardaway
</td>
<td style="text-align:left;">
NYK
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3.85
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>

#### Jason Kosmicki (DEN) 15/16 Improved

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
Gary Harris
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
DEN
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
3.97
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
Will Barton
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
DEN
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
26
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
3.66
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
16
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
9
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
C J McCollum
</td>
<td style="text-align:left;">
POR
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
127
</td>
<td style="text-align:right;">
1.36
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
C J McCollum
</td>
<td style="text-align:left;">
POR
</td>
<td style="text-align:right;">
343
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
127
</td>
<td style="text-align:right;">
1.36
</td>
<td style="text-align:right;">
101
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Kemba Walker
</td>
<td style="text-align:left;">
CHO
</td>
<td style="text-align:right;">
115
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
64
</td>
<td style="text-align:right;">
3.12
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Giannis Antetokounmpo
</td>
<td style="text-align:left;">
MIL
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
3.43
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Stephen Curry
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
56
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
3.57
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
5
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
Will Barton
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
DEN
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
44
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
26
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
3.66
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
16
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
9
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
12
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
Gary Harris
</td>
<td style="text-align:left;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
DEN
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
4
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
3.97
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(77, 144, 205, 255) !important;background-color: rgba(253, 185, 39, 255) !important;">
</td>
</tr>
</tbody>
</table>

#### Ron Tillery (MEM) 16/17 Sixth Man

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
1
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
Zach Randolph
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
MEM
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
26
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
3.64
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
6
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
18
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Andre Iguodala
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
1.94
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Eric Gordon
</td>
<td style="text-align:left;">
HOU
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:right;">
1.74
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Eric Gordon
</td>
<td style="text-align:left;">
HOU
</td>
<td style="text-align:right;">
226
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
94
</td>
<td style="text-align:right;">
1.74
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Andre Iguodala
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
1.94
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Lou Williams
</td>
<td style="text-align:left;">
HOU
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
3.50
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
Zach Randolph
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
MEM
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
36
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
26
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
3.64
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
6
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
18
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
James Johnson
</td>
<td style="text-align:left;">
MIA
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3.80
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
11
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
Vince Carter
</td>
<td style="text-align:left;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
MEM
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
3.99
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
0
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(15, 88, 108, 255) !important;background-color: rgba(115, 153, 198, 255) !important;">
</td>
</tr>
</tbody>
</table>

### Most Anti-Homer Ballots

#### Cedric Maxwell (BOS) 14/15 Sixth Man

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Jamal Crawford
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
3.25
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Lou Williams
</td>
<td style="text-align:left;">
TOR
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
1.60
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Aaron Brooks
</td>
<td style="text-align:left;">
CHI
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3.99
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Lou Williams
</td>
<td style="text-align:left;">
TOR
</td>
<td style="text-align:right;">
312
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
122
</td>
<td style="text-align:right;">
1.60
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Isaiah Thomas
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
212
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
130
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2.37
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
33
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
46
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
21
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Jamal Crawford
</td>
<td style="text-align:left;">
LAC
</td>
<td style="text-align:right;">
97
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
3.25
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Andre Iguodala
</td>
<td style="text-align:left;">
GSW
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Tristan Thompson
</td>
<td style="text-align:left;">
CLE
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
3.79
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>

#### Gary Washburn (BOS) 17/18 Coach

<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Place
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Brett Brown
</td>
<td style="text-align:left;">
PHI
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Nate McMillan
</td>
<td style="text-align:left;">
IND
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Quin Snyder
</td>
<td style="text-align:left;">
UTA
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:right;">
2.55
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<table class="table table-bordered" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Actual
</th>
<th style="text-align:left;">
Player
</th>
<th style="text-align:left;">
Team
</th>
<th style="text-align:right;">
Pts
</th>
<th style="text-align:right;">
Ballots
</th>
<th style="text-align:right;">
Mentions
</th>
<th style="text-align:right;">
Avg Place
</th>
<th style="text-align:right;">
1
</th>
<th style="text-align:right;">
2
</th>
<th style="text-align:right;">
3
</th>
<th style="text-align:right;">
4
</th>
<th style="text-align:right;">
5
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Dwane Casey
</td>
<td style="text-align:left;">
TOR
</td>
<td style="text-align:right;">
187
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
2.13
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Quin Snyder
</td>
<td style="text-align:left;">
UTA
</td>
<td style="text-align:right;">
145
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:right;">
2.55
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
Brad Stevens
</td>
<td style="text-align:left;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
BOS
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
134
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
100
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
65
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
2.66
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
23
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
23
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
19
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
<td style="text-align:right;font-weight: bold;color: rgba(0, 131, 72, 255) !important;background-color: rgba(187, 151, 83, 255) !important;">
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Brett Brown
</td>
<td style="text-align:left;">
PHI
</td>
<td style="text-align:right;">
54
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Nate McMillan
</td>
<td style="text-align:left;">
IND
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>

### 

Cedric Maxwell, the Boston Celtic’s radio color commentator and former NBA Finals MVP for the same team, owns the most anti-homer ballot. This is actually outlier result for Maxwell, as many of his other ballots have high homer scores, giving him a rank of 29 overall for hometown bias. The offending ballot is for 2014/15 Sixth Man of the Year, when he left off Celtic guard Isaiah Thomas. A possible explanation for this may be that Thomas joined Boston midway through the season via trade, playing only 21 games for the Celtics.

The ballot with the second lowest hometown bias score is Darnell Mayberry’s 2014/15 MVP vote, already discussed above. Coming in third is Celtic beat writer Gary Washburn’s 2017/18 Coach of the Year ballot. These are atypical results given the general homerism of the Boston voting bloc. A takeaway from these results is that it takes little to generate a high negative bias score. Because of how the scores are calculated, leaving off a player that finished middle of the pack in the results may lead to a very low score depending on how everyone else votes.

## Parting Thoughts

Given the hometown bias results, the NBA made a justified decision in removing team broadcasters from the panel of award voters. This is not to say that all announcers showed bias in their awards ballots, as there were many announcers that placed at the bottom of the table ranking team-affiliated voters. A good number of these broadcasters are associated with the two New York teams. This is not surprising for anyone who has watched many Knicks and Nets broadcasts, given the even-handedness of their announcing crews. Mark Boyle of the Pacers and George Balaha of the Pistons are a couple of non-New York examples who also score low.

As previously mentioned, international voters were introduced with the removal of broadcasters for the 2016/17 end-of-season awards. While there is no way for international voters to show hometown bias, a few ballots from these media members made you question how much they actually follow the NBA. But that is an idea for a different post.
